# Generated by Django 5.0.7 on 2024-07-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('price', models.IntegerField()),
                ('discount', models.FloatField()),
                ('size', models.CharField(choices=[('xs', 'extra small'), ('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'extra large')], default='m', max_length=2)),
                ('discription', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
