# Generated by Django 5.0.7 on 2024-07-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_student_file_remove_student_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_name", models.CharField(max_length=500)),
                ("speed", models.IntegerField(default=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
